### ISSUE TITLE
keepArrayIndentation not respected

### ISSUE THREAD

**Issue by kirkstrobeck** [fshost/node-beautify#2]
See https://github.com/wearefractal/gulp-beautify/issues/7

I don't believe that this respects the default option of

    keepArrayIndentation : false

as specified on https://github.com/fshost/node-beautify#default-options

Code before:

    var test = [
      '1',
      '2',
      '3'
    ]

after

    var test = ['1', '2', '3']

> If you look here https://github.com/fshost/node-beautify/blob/master/lib/beautify-js.js#L27
>
> The settings object is being mutated globally, so subsequent runs will use the settings of the previous run. 

cc: @Contra

**Comment by fshost** [comment]
I've been asked to deprecate this library in favor of [js-beautify](https://github.com/beautify-web/js-beautify) by the folks behind 
[jsbeautifier.org](http://jsbeautifier.org).  As those developers are the true successors of the original library and you can now require their module within node.js, I have complied.  Please use js-beautify.
